name: fido2_client
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: mojaloop.fido2.fido2_client
        pluginClass: Fido2ClientPlugin
      web:
        pluginClass: Fido2ClientWeb
        fileName: Fido2ClientPlugin_web.dart

  assets:
    - assets/js/fido2_client.js
